### ISSUE TITLE
Query seems to fail code gen for no obvious reason

### ISSUE THREAD

**Issue by gordonwatts** [iris-hep/func_adl_xAOD#39]
Query:

```
 EventSource
  .Select(lambda e353: (e353.Electrons("Electrons"), e353))
  .Select(lambda e366: e366[0].Where(lambda e354: e366[1].TruthParticles("TruthParticles").Select(lambda e361: e361.Count()).Select(lambda e362: (e362 > 0))))
  .Select(lambda e367: e367.Select(lambda e363: e363.pt()))
```

And the qastle code:
```
(call ResultTTree (call Select (call Select (call Select (call EventDataset (list 'localds://mc15_13TeV:mc15_13TeV.361106.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zee.merge.DAOD_STDM3.a0_s2576_s2132_r6630_r6264_p2363_tid05630052_00')) (lambda (list a1) (list (call (attr a1 'Electrons') 'Electrons') a1))) (lambda (list a2) (call (attr (subscript a2 0) 'Where') (lambda (list a3) (call (attr (call (attr (call (attr (subscript a2 1) 'TruthParticles') 'TruthParticles') 'Select') (lambda (list a4) (call (attr a4 'Count')))) 'Select') (lambda (list a5) (> a5 0))))))) (lambda (list a6) (call (attr a6 'Select') (lambda (list a7) (call (attr a7 'pt')))))) (list 'col1') 'treeme' 'file.root')
```

The error from the code generator:

```
(ServiceX_Exception(...), 'ServiceX rejected the transformation request: (400){\'message\': "Failed to submit transform request: Failed to generate translation code: Unable to generate a sequence from the given AST. Either there is an internal error, or you are trying to manipulate a \'cpp_value\' as a sequence (ast is: Name(id=\'arg_194\', ctx=Load()))"}')
```

And the log from the codgen container:

```
------> (call ResultTTree (call Select (call Select (call Select (call EventDataset (list 'localds://mc15_13TeV:mc15_13TeV.361106.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zee.merge.DAOD_STDM3.a0_s2576_s2132_r6630_r6264_p2363_tid05630052_00')) (lambda (
list a1) (list (call (attr a1 'Electrons') 'Electrons') a1))) (lambda (list a2) (call (attr (subscript a2 0) 'Where') (lambda (list a3) (call (attr (call (attr (call (attr (subscript a2 1) 'TruthParticles') 'TruthParticles') 'Select') (lambda (
list a4) (call (attr a4 'Count')))) 'Select') (lambda (list a5) (> a5 0))))))) (lambda (list a6) (call (attr a6 'Select') (lambda (list a7) (call (attr a7 'pt')))))) (list 'col1') 'treeme' 'file.root') [<_ast.Expr object at 0x7f10017bc8d0>]
------> <func_adl_xAOD.backend.xAODlib.atlas_xaod_executor.atlas_xaod_executor object at 0x7f100117a190>
Unable to generate a sequence from the given AST. Either there is an internal error, or you are trying to manipulate a 'cpp_value' as a sequence (ast is: Name(id='arg_194', ctx=Load()))
Traceback (most recent call last):
  File "/home/servicex/servicex/code_generator_service/generate_code.py", line 42, in post
    zip_data = self.translator.translate_text_ast_to_zip(code)
  File "/home/servicex/servicex/code_generator_service/ast_translator.py", line 114, in translate_text_ast_to_zip
    r = self.get_generated_xAOD(a, tempdir)
  File "/home/servicex/servicex/code_generator_service/ast_translator.py", line 84, in get_generated_xAOD
    f_spec = exe.write_cpp_files(exe.apply_ast_transformations(a), query_file_path)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/atlas_xaod_executor.py", line 105, in write_cpp_files
    result_rep = qv.get_rep(ast)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 175, in get_rep
    self.generic_visit(node) if use_generic_visit else self.visit(node)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 144, in visit
    r = FuncADLNodeVisitor.visit(self, node)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 520, in visit_Call
    r = FuncADLNodeVisitor.visit_Call(self, call_node)
  File "/usr/local/lib/python3.7/site-packages/func_adl/ast/func_adl_ast_utils.py", line 78, in visit_Call
    return visitor(node, args)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 685, in call_ResultTTree
    self.generic_visit(source)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 144, in visit
    r = FuncADLNodeVisitor.visit(self, node)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/ast.py", line 281, in generic_visit
    self.visit(value)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 144, in visit
    r = FuncADLNodeVisitor.visit(self, node)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 520, in visit_Call
    r = FuncADLNodeVisitor.visit_Call(self, call_node)
  File "/usr/local/lib/python3.7/site-packages/func_adl/ast/func_adl_ast_utils.py", line 78, in visit_Call
    return visitor(node, args)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 802, in call_Select
    seq = self.as_sequence(source)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 237, in as_sequence
    rep = self.get_rep(generation_ast)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 175, in get_rep
    self.generic_visit(node) if use_generic_visit else self.visit(node)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 144, in visit
    r = FuncADLNodeVisitor.visit(self, node)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 520, in visit_Call
    r = FuncADLNodeVisitor.visit_Call(self, call_node)
  File "/usr/local/lib/python3.7/site-packages/func_adl/ast/func_adl_ast_utils.py", line 78, in visit_Call
    return visitor(node, args)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 859, in call_Where
    rep = self.get_rep(c)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 175, in get_rep
    self.generic_visit(node) if use_generic_visit else self.visit(node)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 144, in visit
    r = FuncADLNodeVisitor.visit(self, node)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 511, in visit_Call
    self.visit_Call_Lambda(call_node)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 265, in visit_Call_Lambda
    call_node.rep = self.get_rep(call_node.func.body)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 175, in get_rep
    self.generic_visit(node) if use_generic_visit else self.visit(node)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 144, in visit
    r = FuncADLNodeVisitor.visit(self, node)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 520, in visit_Call
    r = FuncADLNodeVisitor.visit_Call(self, call_node)
  File "/usr/local/lib/python3.7/site-packages/func_adl/ast/func_adl_ast_utils.py", line 78, in visit_Call
    return visitor(node, args)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 807, in call_Select
    new_sequence_value = self.get_rep(c)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 175, in get_rep
    self.generic_visit(node) if use_generic_visit else self.visit(node)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 144, in visit
    r = FuncADLNodeVisitor.visit(self, node)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 511, in visit_Call
    self.visit_Call_Lambda(call_node)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 265, in visit_Call_Lambda
    call_node.rep = self.get_rep(call_node.func.body)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 175, in get_rep
    self.generic_visit(node) if use_generic_visit else self.visit(node)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 144, in visit
    r = FuncADLNodeVisitor.visit(self, node)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 626, in visit_Compare
    left = self.get_rep(node.left)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 175, in get_rep
    self.generic_visit(node) if use_generic_visit else self.visit(node)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 144, in visit
    r = FuncADLNodeVisitor.visit(self, node)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 520, in visit_Call
    r = FuncADLNodeVisitor.visit_Call(self, call_node)
  File "/usr/local/lib/python3.7/site-packages/func_adl/ast/func_adl_ast_utils.py", line 78, in visit_Call
    return visitor(node, args)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 455, in call_Aggregate
    return self.visit_call_Aggregate_initial(node, args)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 353, in visit_call_Aggregate_initial
    seq = self.as_sequence(raw_seq)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 255, in as_sequence
    raise BaseException(f"Unable to generate a sequence from the given AST. Either there is an internal error, or you are trying to manipulate a '{type(rep).__name__}' as a sequence (ast is: {ast.dump(generation_ast)})")
BaseException: Unable to generate a sequence from the given AST. Either there is an internal error, or you are trying to manipulate a 'cpp_value' as a sequence (ast is: Name(id='arg_194', ctx=Load()))
192.168.21.58 - - [13/Apr/2020:21:46:09 +0000] "POST /servicex/generated-code HTTP/1.1" 500 201 "-" "python-requests/2.23.0"
```

**Comment by gordonwatts** [comment]
As it turns out, this backend is doing what it should be doing - look at this line:

```
  .Select(lambda e366: e366[0].Where(lambda e354: e366[1].TruthParticles("TruthParticles").Select(lambda e361: e361.Count()).Select(lambda e362: (e362 > 0))))
```

Look at the `Count()` - there it is operating on e361. But e361 is actually a single truth particle, not all the particles. So the code that generated this made an error and tried to count a single object.

That said, the error could have been a little better so help focus where we were looking!
